language: php
sudo: false
php:
    - 5.5
    - 5.6
    - 7.0
cache:
  directories:
    - $HOME/.composer/cache
before_install:
  - travis_retry composer self-update
install:
  - travis_retry composer update --no-interaction --prefer-source
script:
  - composer test